// auto-generated by: gulp generate-definition-file
declare module "ts-type-info" {
    export interface Options {
        compilerOptions: CompilerOptions;
    }

    export interface CompilerOptions {
        allowNonTsExtensions: boolean;
        charset: string;
        locale: string;
        project: string;
        rootDir: string;
    }

    export interface IBaseNamedDefinition {
        name: string;
    }

    export interface INamedDefinition extends IBaseNamedDefinition {
    }

    export interface ITypeExpressionedDefinition {
        typeExpression: TypeExpression;
    }

    export interface IDefaultExpressionedDefinition {
        defaultExpression: Expression;
    }

    export interface IDecoratableDefinition {
        decorators: DecoratorDefinition[];
    }

    export interface IExportableDefinition {
        isExported: boolean;
    }

    export interface IModuledDefinition {
        namespaces: NamespaceDefinition[];
        classes: ClassDefinition[];
        interfaces: InterfaceDefinition[];
        enums: EnumDefinition[];
        functions: FunctionDefinition[];
        variables: VariableDefinition[];
    }

    export interface ITypeParameteredDefinition {
        typeParameters: TypeParameterDefinition[];
    }

    export interface BaseParameterDefinitionConstructor<T> {
    }

    export interface IParameteredDefinition<T> {
        parameters: T[];
    }

    export interface IReturnTypedDefinition {
        returnTypeExpression: TypeExpression;
    }

    export interface IScopedDefinition {
        scope: Scope;
    }

    export class NamedDefinition {
        name: string;
    }

    export class TypeExpressionedDefinition {
        typeExpression: TypeExpression;
    }

    export class DefaultExpressionedDefinition {
        defaultExpression: Expression;
    }

    export class DecoratableDefinition {
        decorators: DecoratorDefinition[];
    }

    export class ExportableDefinition {
        isExported: boolean;
    }

    export class ModuledDefinition {
        namespaces: NamespaceDefinition[];
        classes: ClassDefinition[];
        interfaces: InterfaceDefinition[];
        enums: EnumDefinition[];
        functions: FunctionDefinition[];
        variables: VariableDefinition[];
    }

    export class BasePropertyDefinition {
        isOptional: boolean;
        name: string;
        typeExpression: TypeExpression;
    }

    export class TypeParameteredDefinition {
        typeParameters: TypeParameterDefinition[];
    }

    export class TypeParameterDefinition {
        constraintTypeExpression: TypeExpression;
        name: string;
    }

    export class ObjectPropertyDefinition extends BasePropertyDefinition {
        defaultExpression: Expression;
    }

    export class DecoratorDefinition {
        name: string;
        arguments: Expression[];
    }

    export class BaseFunctionDefinition<T> {
        name: string;
        parameters: T[];
        returnTypeExpression: TypeExpression;
        typeParameters: TypeParameterDefinition[];
    }

    export class BaseParameterDefinition {
        isOptional: boolean;
        isRestParameter: boolean;
        name: string;
        typeExpression: TypeExpression;
        defaultExpression: Expression;
    }

    export class ParameteredDefinition<T> {
        parameters: T[];
    }

    export class ReturnTypedDefinition {
        returnTypeExpression: TypeExpression;
    }

    export class CallSignatureDefinition {
        minArgumentCount: number;
        parameters: ParameterDefinition[];
        returnTypeExpression: TypeExpression;
        typeParameters: TypeParameterDefinition[];
    }

    export class FunctionDefinition extends BaseFunctionDefinition<ParameterDefinition> {
        isExported: boolean;
    }

    export class ParameterDefinition extends BaseParameterDefinition {
    }

    export class BaseClassMethodDefinition extends BaseFunctionDefinition<ClassMethodParameterDefinition> {
        decorators: DecoratorDefinition[];
        scope: Scope;
    }

    export class BaseClassPropertyDefinition extends ObjectPropertyDefinition {
        decorators: DecoratorDefinition[];
        scope: Scope;
    }

    export class ScopedDefinition {
        scope: Scope;
    }

    export class ClassDefinition {
        methods: ClassMethodDefinition[];
        properties: ClassPropertyDefinition[];
        staticMethods: ClassStaticMethodDefinition[];
        staticProperties: ClassStaticPropertyDefinition[];
        constructorDef: ConstructorDefinition;
        typeParameters: TypeParameterDefinition[];
        extendsTypeExpressions: TypeExpression[];
        implementsTypeExpressions: TypeExpression[];
        name: string;
        decorators: DecoratorDefinition[];
        isExported: boolean;
    }

    export class ClassMethodDefinition extends BaseClassMethodDefinition {
    }

    export class ClassMethodParameterDefinition extends BaseParameterDefinition {
        decorators: DecoratorDefinition[];
    }

    export class ClassPropertyDefinition extends BaseClassPropertyDefinition {
        isAccessor: boolean;
        isReadonly: boolean;
    }

    export class ConstructorDefinition {
        parameters: ClassMethodParameterDefinition[];
    }

    export class ClassStaticMethodDefinition extends BaseClassMethodDefinition {
    }

    export class ClassStaticPropertyDefinition extends BaseClassPropertyDefinition {
    }

    export class InterfaceDefinition {
        methods: InterfaceMethodDefinition[];
        newSignatures: InterfaceNewSignatureDefinition[];
        properties: InterfacePropertyDefinition[];
        typeParameters: TypeParameterDefinition[];
        extendsTypeExpressions: TypeExpression[];
        name: string;
        isExported: boolean;
    }

    export class InterfaceMethodDefinition extends BaseFunctionDefinition<ParameterDefinition> {
    }

    export class InterfacePropertyDefinition extends BasePropertyDefinition {
    }

    export class InterfaceNewSignatureDefinition {
        parameters: ParameterDefinition[];
        returnTypeExpression: TypeExpression;
    }

    export class EnumDefinition {
        members: EnumMemberDefinition[];
        name: string;
        isExported: boolean;
    }

    export class EnumMemberDefinition {
        value: number;
        name: string;
    }

    export class NamespaceDefinition {
        declarationType: NamespaceDeclarationType;
        name: string;
        namespaces: NamespaceDefinition[];
        classes: ClassDefinition[];
        interfaces: InterfaceDefinition[];
        enums: EnumDefinition[];
        functions: FunctionDefinition[];
        variables: VariableDefinition[];
        isExported: boolean;
    }

    export class FileDefinition {
        fileName: string;
        imports: ImportDefinition[];
        reExports: ReExportDefinition[];
        name: string;
        namespaces: NamespaceDefinition[];
        classes: ClassDefinition[];
        interfaces: InterfaceDefinition[];
        enums: EnumDefinition[];
        functions: FunctionDefinition[];
        variables: VariableDefinition[];
    }

    export class ImportDefinition {
        file: FileDefinition;
        definition: IBaseNamedDefinition & IExportableDefinition;
    }

    export class ReExportDefinition {
        file: FileDefinition;
        definition: IBaseNamedDefinition & IExportableDefinition;
    }

    export class VariableDefinition {
        declarationType: VariableDeclarationType;
        name: string;
        isExported: boolean;
        typeExpression: TypeExpression;
        defaultExpression: Expression;
    }

    export class Expression {
        text: string;
    }

    export class Type {
        callSignatures: CallSignatureDefinition[];
        definition: IBaseNamedDefinition;
        properties: BasePropertyDefinition[];
        typeArguments: TypeExpression[];
        text: string;
    }

    export class TypeExpression {
        text: string;
        types: Type[];
    }

    export enum Scope {
        public = 0,
        protected = 1,
        private = 2
    }

    export enum NamespaceDeclarationType {
        Namespace = 0,
        Module = 1
    }

    export enum VariableDeclarationType {
        Var = 0,
        Let = 1,
        Const = 2
    }

    export function getFileInfo(fileNames: string[], options?: Options): FileDefinition[];
    export function getStringInfo(code: string, options?: Options): FileDefinition;
}
