import {ClassConstructorParameterScope, NamespaceDeclarationType, Scope, VariableDeclarationType} from "./../definitions";
import {IExpression} from "./expression";
import {ITypeExpression} from "./type-expression";
import {ISignature} from "./signature";
import {ISymbol} from "./symbol";
import {ISourceFileChild} from "./source-file-child";

export interface INode extends ISourceFileChild {
    forEachChild(callback: (node: INode) => void): void;
    getClassConstructorParameterScope(): ClassConstructorParameterScope;
    getConstantValue(): number;
    getDecorators(): INode[];
    getDecoratorName(): string;
    getDecoratorArguments(): IExpression[];
    getDefaultExpression(): IExpression;
    getDefaultImportNameAndSymbol(): { name: string; symbol: ISymbol; };
    getExpression(): IExpression;
    getFileNameOfModuleSpecifier(): string;
    getHeritageNodes(): INode[];
    getImplementsTypeExpressions(): ITypeExpression[];
    getLocalSymbol(): ISymbol;
    getModuleSpecifierText(): string;
    getModuleSpecifierSymbol(): ISymbol;
    getName(): string;
    getNamedImportSymbolsByName(): { [name: string]: ISymbol; };
    getNamedExportSymbolsByName(): { [name: string]: ISymbol; };
    getNamespaceDeclarationType(): NamespaceDeclarationType;
    getParameters(): INode[];
    getReturnTypeExpression(): ITypeExpression;
    getScope(): Scope;
    getSignatureFromThis(): ISignature;
    getStarImportName(): string;
    getStarSymbol(): ISymbol;
    getSymbol(): ISymbol;
    getTypeExpression(): ITypeExpression;
    getTypeParameters(): INode[];
    getTypeParameterConstraintTypeExpression(): ITypeExpression;
    getTypes(): ITypeExpression[];
    getVariableDeclarationType(): VariableDeclarationType;
    hasAbstractKeyword(): boolean;
    hasDeclareKeyword(): boolean;
    hasStaticKeyword(): boolean;
    isAmbient(): boolean;
    isClass(): boolean;
    isConstructor(): boolean;
    isConstructorParameter(): boolean;
    isConstructSignature(): boolean;
    isDefaultKeyword(): boolean;
    isEnum(): boolean;
    isExportDeclaration(): boolean;
    isExportKeyword(): boolean;
    isExportAssignment(): boolean;
    isFunction(): boolean;
    isFunctionType(): boolean;
    isGetAccessor(): boolean;
    isIdentifier(): boolean;
    isImport(): boolean;
    isInterface(): boolean;
    isMethodDeclaration(): boolean;
    isMethodSignature(): boolean;
    isNamespace(): boolean;
    isParameterOptional(): boolean;
    isPropertyOptional(): boolean;
    isRestParameter(): boolean;
    isPropertyDeclaration(): boolean;
    isPropertySignature(): boolean;
    isSetAccessor(): boolean;
    isStarImport(): boolean;
    isTypeAlias(): boolean;
    isTypeParameter(): boolean;
    isVariable(): boolean;
    nodeKindToString(): string;
}
