export * from "./base/run-base-property-definition-tests";
export * from "./base/run-ambientable-definition-tests";
export * from "./base/run-decoratable-definition-tests";
export * from "./base/run-default-expressioned-definition-tests";
export * from "./base/run-exportable-definition-tests";
export * from "./base/run-moduled-definition-tests";
export * from "./base/run-named-definition-tests";
export * from "./base/run-type-expressioned-definition-tests";
export * from "./base/run-type-parametered-definition-tests";
