export * from "./structure/base";
export * from "./structure/class";
export * from "./structure/enum";
export * from "./structure/expressions";
export * from "./structure/function";
export * from "./structure/general";
export * from "./structure/interface";
export * from "./structure/namespace";
export * from "./structure/variable";
